name: debugging

on:
  push:
    branches:
      - main
      - 'github-actions-pipeline'

jobs:

  ###############################################
  #
  #    Build jobs starts here
  #
  ###############################################
  Build:
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: before script
      run: |
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)/build/third-party/lib:$(pwd)/build/lib
        if [[ ${COMPILER^^} == "CLANG" ]]; then export CC=/usr/bin/clang-9; export CXX=/usr/bin/clang++-9; else export CC=gcc-7; export CXX=g++-7; fi
        if [ -n ${NATIVE_BACKEND} ]; then export NATIVE_SIZE=-DNATIVE_SIZE\=${NATIVE_BACKEND}; else export NATIVE_SIZE=""; fi
        echo ${NATIVE_SIZE}
        export CMAKE_ARGS=${NATIVE_SIZE}
        echo ${CMAKE_ARGS}

    - name: debug_mb2_build
      run: |
        whoami
        mkdir -p build
        cd build
        cmake ${CMAKE_ARGS} -DBUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug -DMATHBACKEND=2 ..
        make -j $(nproc) all
        make allextras
    - name: debug_mb2_build-upload-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: debug_mb2_build-artifact
        path: |
          build/third-party/lib
          build/lib
          build/unittest
          build/bin/benchmark
          build/bin/extras
        retention-days: 1
    - run: ls -alh
    - run: rm -rf build
    - run: ls -alh

  Build_test:
    needs: Build
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
    steps:
    # -- debug_mb2_test_binfhe
    - name: download-debug_mb2_build-artifact
      uses: actions/download-artifact@v2
      with:
        name: debug_mb2_build-artifact
        path: build/
    - name: debug_mb2_test_binfhe
      run: |
        ls -alh build/
        chmod -R +x build/
        pwd
        echo $LD_LIBRARY_PATH
        build/unittest/binfhe_tests --gtest_output=xml
    - name: debug_mb2_test_binfhe-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: debug_mb2_test_binfhe-artifact
        path: |
          test_detail.xml
        retention-days: 2
