name: Build and Deploy Dev Api

on:
  push:
    branches:
      - main
      - 'github-actions-pipeline'

jobs:
  docker:
    runs-on: [self-hosted, linux, x64, 'ubuntu20']
    env:
      GIT_SUBMODULE_STRATEGY: recursive
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: before script
      run: |
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)/build/third-party/lib:$(pwd)/build/lib
        if [[ ${COMPILER^^} == "CLANG" ]]; then export CC=/usr/bin/clang-9; export CXX=/usr/bin/clang++-9; else export CC=gcc-7; export CXX=g++-7; fi
        if [ -n ${NATIVE_BACKEND} ]; then export NATIVE_SIZE=-DNATIVE_SIZE\=${NATIVE_BACKEND}; else export NATIVE_SIZE=""; fi
        echo ${NATIVE_SIZE}
        export CMAKE_ARGS=${NATIVE_SIZE}
        echo ${CMAKE_ARGS}