name: Main

on:
  push:
    branches:
      - main

env:
  CMAKE_ARGS: "-DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_C_COMPILER=/usr/bin/gcc-9"

jobs:
  
  call_basic_workflow:
    uses: openfheorg/openfhe-temp/.github/workflows/reuseable_workflow.yml@jsaylor/additions-to-ci-cd
    with:
      mb2_debug: true
      mb2_tcm: true
      mb4_noflag: true
      mb4_debug: true
      mb4_tcm: true
      mb6_ntl_noflag: true
      mb6_ntl_debug_tcm: true
      mb6_ntl_tcm: true

  mb2_128:
    needs: call_basic_workflow
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb2_128
      uses: ./.github/actions/default_builder
      with:
        module_name: mb4_tcm
        # cmake_args: ${{ env.CMAKE_ARGS }} -DBUILD_EXTRAS=ON -DWITH_TCM=ON -DMATHBACKEND=4 
        native_backend: 128
        mathbackend: 2
        run_extras: true

  mb2_clang:
    needs: mb2_128
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb2_128
      uses: ./.github/actions/default_builder
      with:
        module_name: mb4_tcm
        cmake_args: "-DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10"
        run_extras: true


  ###############################################
  #
  #    Pages jobs starts here
  #
  ###############################################
  pages:
    needs: mb2_clang
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: build_docs
      run: |
        whoami
        cmake -S . -B build -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_C_COMPILER=/usr/bin/gcc-9
        pushd build
        make apidocs
        popd
        mv doc/apidocs/html/ docs/

    - name: deploy_docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
