name: Run on pull-request

on:
  pull_request:
    branches:
      - main

env:
  CMAKE_ARGS: "-DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_C_COMPILER=/usr/bin/gcc-9"

jobs:

  call_basic_workflow:
    uses: openfheorg/openfhe-temp/.github/workflows/reuseable_workflow.yml@jsaylor/additions-to-ci-cd
