name: Build PALISADE pull-request

on:
  pull_request:
    branches:
      - main

jobs:

  ###############################################
  #
  #    debug_mb2 jobs starts here
  #
  ###############################################
  debug_mb2:
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
      CMAKE_ARGS: 'DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    #debug_mb2_build
    - name: debug_mb2
      uses: ./.github/actions/default_builder
      with:
        module_name: debug_mb2
        cmake-args: ${CMAKE_ARGS} -DBUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug -DMATHBACKEND=2 ..


  ###############################################
  #
  #    debug_mb4 jobs starts here
  #
  ###############################################
  debug_mb4:
    needs: debug_mb2
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
      CMAKE_ARGS: 'DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    #debug_mb4_build
    - name: debug_mb4
      uses: ./.github/actions/default_builder
      with:
        module_name: debug_mb4
        cmake-args: cmake ${CMAKE_ARGS} -DBUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug -DMATHBACKEND=4 ..

  ###############################################
  #
  #    debug_tcm_ntl_mb6 jobs starts here
  #
  ###############################################
  debug_tcm_ntl_mb6:
    needs: debug_mb4
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
      CMAKE_ARGS: 'DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    #debug_tcm_ntl_mb6_build
    - name: debug_tcm_ntl_mb6
      uses: ./.github/actions/default_builder
      with:
        module_name: debug_tcm_ntl_mb6
        cmake-args: cmake ${CMAKE_ARGS} -DBUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_NTL=Y -DWITH_TCM=Y -DMATHBACKEND=6 ..


  ###############################################
  #
  #    default jobs starts here
  #
  ###############################################
  default:
    needs: debug_tcm_ntl_mb6
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
      CMAKE_ARGS: 'DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    #default_build
    - name: default
      uses: ./.github/actions/default_builder
      with:
        module_name: default
        cmake-args: cmake ${CMAKE_ARGS} ..


  ###############################################
  #
  #    noflag_mb4 jobs starts here
  #
  ###############################################
  noflag_mb4:
    needs: default
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
      CMAKE_ARGS: 'DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    #noflag_mb4_build
    - name: noflag_mb4
      uses: ./.github/actions/default_builder
      with:
        module_name: noflag_mb4
        cmake-args: cmake ${CMAKE_ARGS} -DBUILD_EXTRAS=ON -DMATHBACKEND=4 ..


  ###############################################
  #
  #    ntl_mb6 jobs starts here
  #
  ###############################################
  ntl_mb6:
    needs: noflag_mb4
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
      CMAKE_ARGS: 'DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    #ntl_mb6_build
    - name: ntl_mb6
      uses: ./.github/actions/default_builder
      with:
        module_name: ntl_mb6
        cmake-args: cmake ${CMAKE_ARGS} -DBUILD_EXTRAS=ON -DWITH_NTL=Y -DMATHBACKEND=6 ..


  ###############################################
  #
  #    tcm_mb2 jobs starts here
  #
  ###############################################
  tcm_mb2:
    needs: ntl_mb6
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
      CMAKE_ARGS: 'DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    #tcm_mb2_build
    - name: tcm_mb2
      uses: ./.github/actions/default_builder
      with:
        module_name: tcm_mb2
        cmake-args: cmake ${CMAKE_ARGS} -DBUILD_EXTRAS=ON -DWITH_TCM=Y -DMATHBACKEND=2 ..
        run_beanchmark: true


  ###############################################
  #
  #    tcm_mb4 jobs starts here
  #
  ###############################################
  tcm_mb4:
    needs: tcm_mb2
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
      CMAKE_ARGS: 'DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    #tcm_mb4_build
    - name: tcm_mb4
      uses: ./.github/actions/default_builder
      with:
        module_name: tcm_mb4
        cmake-args: cmake ${CMAKE_ARGS} -DBUILD_EXTRAS=ON -DWITH_TCM=Y -DMATHBACKEND=4 ..


  ###############################################
  #
  #    tcm_ntl_mb6 jobs starts here
  #
  ###############################################
  tcm_ntl_mb6:
    needs: tcm_mb4
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
      CMAKE_ARGS: 'DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    #tcm_ntl_mb6_build
    - name: tcm_ntl_mb6
      uses: ./.github/actions/default_builder
      with:
        module_name: tcm_ntl_mb6
        cmake-args: cmake ${CMAKE_ARGS} -DBUILD_EXTRAS=ON -DWITH_NTL=Y -DWITH_TCM=Y -DMATHBACKEND=6 ..


  ###############################################
  #
  #    Pages jobs starts here
  #
  ###############################################
  pages:
    needs: tcm_ntl_mb6
    runs-on: [self-hosted, Linux, X64]
    env:
      GIT_SUBMODULE_STRATEGY: recursive
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: build_docs
      run: |
        whoami
        mkdir -p build
        cd build
        cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_C_COMPILER=/usr/bin/gcc-9 ..
        make apidocs
        cd ..
        mv doc/apidocs/html/ docs/

    - name: deploy_docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs